### ISSUE TITLE
module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by AlexRMU** [eridgd/WCT-TF#32]
```
2020-04-29 06:51:30.773744: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Using TensorFlow backend.
Traceback (most recent call last):
  File "stylize.py", line 126, in <module>
    main()
  File "stylize.py", line 51, in main
    ss_stride=args.ss_stride)
  File "/content/WCT-TF/wct.py", line 29, in __init__
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

**Comment by eridgd** [comment]
This seems like a TF version issue, try using a TF 1.x release, or changing the line to:
```
graph = tf.compat.v1.get_default_graph()
```
https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_default_graph

**Comment by AlexRMU** [comment]
I changed these .py files and everything worked
[model.txt](https://github.com/eridgd/WCT-TF/files/4739719/model.txt)
[wct.txt](https://github.com/eridgd/WCT-TF/files/4739720/wct.txt)
(just change .txt on .py)
but then there was this:
`!python stylize.py --checkpoints models/relu5_1 models/relu4_1 models/relu3_1 models/relu2_1 models/relu1_1 --relu-targets relu5_1 relu4_1 relu3_1 relu2_1 relu1_1 --vgg-path /content/WCT-TF/models/vgg_normalised.t7  --style-path /content/WCT-TF/style --content-path /content/WCT-TF/content --out-path /content/WCT-TF/output                                                                                                    `
```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.

Instructions for updating:

non-resource variables are not supported in the long term

Using TensorFlow backend.

Loading VGG up to layer relu5_1

Traceback (most recent call last):

  File "stylize.py", line 126, in <module>

    main()

  File "stylize.py", line 51, in main

    ss_stride=args.ss_stride)

  File "/content/WCT-TF/wct.py", line 39, in __init__

    ss_patch_size=self.ss_patch_size, ss_stride=self.ss_stride)

  File "/content/WCT-TF/model.py", line 65, in __init__

    self.vgg_model = vgg_from_t7(vgg_path, target_layer=deepest_target)

  File "/content/WCT-TF/vgg_normalised.py", line 38, in vgg_from_t7

    trainable=False)(x)

  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))

  File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 141, in build
    constraint=self.kernel_constraint)

  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),

TypeError: <lambda>() got an unexpected keyword argument 'dtype'

```
