### ISSUE TITLE
Attempted to use a closed Session.

### ISSUE THREAD

**Issue by SolicTous** [eridgd/WCT-TF#34]
I have an issue with Attempt to use a closed Session in the line with "queue_input_val: val_batch"
What is the reason, by which it happens.

.................
Step: 99  LR: 0.0001000  Feature: 21.95053  Pixel: 0.33819  TV: 0.00000  Time: 0.18408
Step: 100  LR: 0.0001000  Feature: 18.16217  Pixel: 0.31331  TV: 0.00000  Time: 0.17411
Model saved in file: /home/developer/PycharmProjects/WCT-TF/models/trained/relu1_1/model.ckpt-100
2020-10-01 15:43:06.942311: W tensorflow/core/kernels/queue_base.cc:285] _1_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.CancelledError'>, Dequeue operation was cancelled
         [[{{node fifo_queue_Dequeue}}]]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 116, in enqueue
    queue_input_val:     val_batch})
  File "/home/developer/PycharmProjects/Inpaint_PConv-Keras/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/developer/PycharmProjects/Inpaint_PConv-Keras/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1075, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

**Comment by SolicTous** [comment]
I have tried to replace unqueue in with.... but didn't help
