### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by emperor1412** [eridgd/WCT-TF#5]
Hi, I follow steps as the document, and got this error while trying to run stylize.py

`C:\Project_GIT\WCT-TF\WCT-TF>python stylize.py --checkpoints models/relu5_1 models/relu4_1 models/relu3_1 models/relu2_1 models/relu1_1 --relu-targets relu5_1 relu4_1 relu3_1 relu2_1 relu1_1 --style-size 512 --alpha 0.8 --style-path C:\Project_GIT\WCT-TF\WCT-TF\style_images\ --content-path C:\Project_GIT\WCT-TF\WCT-TF\content\ --vgg-path C:\Project_GIT\WCT-TF\WCT-TF\models\vgg_normalised.t7`

`Using TensorFlow backend.
Loading VGG up to layer relu5_1
Traceback (most recent call last):
  File "stylize.py", line 120, in <module>
    main()
  File "stylize.py", line 44, in main
    device=args.device)
  File "C:\Project_GIT\WCT-TF\WCT-TF\wct.py", line 27, in __init__
    self.model = WCTModel(mode='test', relu_targets=relu_targets, vgg_path=vgg_path)
  File "C:\Project_GIT\WCT-TF\WCT-TF\model.py", line 57, in __init__
    self.vgg_model = vgg_from_t7(vgg_path, target_layer=deepest_target)
  File "C:\Project_GIT\WCT-TF\WCT-TF\vgg_normalised.py", line 16, in vgg_from_t7
    t7 = torchfile.load(t7_file, force_8bytes_long=False)
  File "C:\Users\emper\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\emper\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\emper\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 385, in read_obj
    k = self.read_obj()
  File "C:\Users\emper\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\emper\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\emper\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'list'`

Do you have any idea ?  Thanks a lot

**Comment by eridgd** [comment]
This appears to be due to Windows incompatibility with the torchfile package, see this issue from someone attempting to use the same vgg_normalised.t7 model https://github.com/bshillingford/python-torchfile/issues/12

Unfortunately, I don't have access to Windows, so until the torchfile author makes it compatible I'd suggest using a Linux VM.

**Comment by eridgd** [comment]
I've gotten access to a Windows VM and will see if there's a simple solution to get this working. If not, I'll try to convert it to TF/Keras and circumvent torchfile.

**Comment by emperor1412** [comment]
Thanks @eridgd , what a nice project

**Comment by eridgd** [comment]
Thanks @xdaimon for the fix!

@emperor1412 I've created a new branch with the modified torchfile.py bundled and one other tweak required to load the model on Windows https://github.com/eridgd/WCT-TF/tree/windows-compat. Can you please check if this works now?

**Comment by xdaimon** [comment]
@eridgd  The windows-compat branch works.
I forgot to mention the small edit in vgg_normalized.py :)
